# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/sIBL_GUI_Updater.ui'
#
# Created: Wed Jun 17 22:19:12 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_sIBL_GUI_Updater_Form(object):
        def setupUi(self, sIBL_GUI_Updater_Form):
                sIBL_GUI_Updater_Form.setObjectName("sIBL_GUI_Updater_Form")
                sIBL_GUI_Updater_Form.resize(800, 600)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/sIBL_GUI FTP/Resources/Icon_Light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                sIBL_GUI_Updater_Form.setWindowIcon(icon)
                self.sIBL_GUI_Updater_Form_gridLayout = QtGui.QGridLayout(sIBL_GUI_Updater_Form)
                self.sIBL_GUI_Updater_Form_gridLayout.setObjectName("sIBL_GUI_Updater_Form_gridLayout")
                self.Buttons_horizontalLayout = QtGui.QHBoxLayout()
                self.Buttons_horizontalLayout.setObjectName("Buttons_horizontalLayout")
                spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Buttons_horizontalLayout.addItem(spacerItem)
                self.Downloads_groupBox = QtGui.QGroupBox(sIBL_GUI_Updater_Form)
                self.Downloads_groupBox.setObjectName("Downloads_groupBox")
                self.Downloads_gridLayout = QtGui.QGridLayout(self.Downloads_groupBox)
                self.Downloads_gridLayout.setObjectName("Downloads_gridLayout")
                self.Open_Repository_pushButton = QtGui.QPushButton(self.Downloads_groupBox)
                self.Open_Repository_pushButton.setObjectName("Open_Repository_pushButton")
                self.Downloads_gridLayout.addWidget(self.Open_Repository_pushButton, 0, 0, 1, 1)
                self.Get_Latest_Templates_pushButton = QtGui.QPushButton(self.Downloads_groupBox)
                self.Get_Latest_Templates_pushButton.setObjectName("Get_Latest_Templates_pushButton")
                self.Downloads_gridLayout.addWidget(self.Get_Latest_Templates_pushButton, 0, 1, 1, 1)
                self.Buttons_horizontalLayout.addWidget(self.Downloads_groupBox)
                self.Close_groupBox = QtGui.QGroupBox(sIBL_GUI_Updater_Form)
                self.Close_groupBox.setObjectName("Close_groupBox")
                self.Close_gridLayout = QtGui.QGridLayout(self.Close_groupBox)
                self.Close_gridLayout.setObjectName("Close_gridLayout")
                self.Close_pushButton = QtGui.QPushButton(self.Close_groupBox)
                self.Close_pushButton.setObjectName("Close_pushButton")
                self.Close_gridLayout.addWidget(self.Close_pushButton, 0, 1, 1, 1)
                self.Buttons_horizontalLayout.addWidget(self.Close_groupBox)
                self.sIBL_GUI_Updater_Form_gridLayout.addLayout(self.Buttons_horizontalLayout, 3, 0, 1, 1)
                self.Message_groupBox = QtGui.QGroupBox(sIBL_GUI_Updater_Form)
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setWeight(75)
                font.setBold(True)
                self.Message_groupBox.setFont(font)
                self.Message_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Message_groupBox.setFlat(True)
                self.Message_groupBox.setObjectName("Message_groupBox")
                self.Message_gridLayout = QtGui.QGridLayout(self.Message_groupBox)
                self.Message_gridLayout.setMargin(0)
                self.Message_gridLayout.setObjectName("Message_gridLayout")
                self.sIBL_GUI_Updater_Form_gridLayout.addWidget(self.Message_groupBox, 1, 0, 1, 1)
                self.Releases_splitter = QtGui.QSplitter(sIBL_GUI_Updater_Form)
                self.Releases_splitter.setOrientation(QtCore.Qt.Vertical)
                self.Releases_splitter.setObjectName("Releases_splitter")
                self.sIBL_GUI_groupBox = QtGui.QGroupBox(self.Releases_splitter)
                self.sIBL_GUI_groupBox.setObjectName("sIBL_GUI_groupBox")
                self.sIBL_GUI_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_GUI_groupBox)
                self.sIBL_GUI_groupBox_gridLayout.setObjectName("sIBL_GUI_groupBox_gridLayout")
                self.Your_Version_groupBox = QtGui.QGroupBox(self.sIBL_GUI_groupBox)
                self.Your_Version_groupBox.setObjectName("Your_Version_groupBox")
                self.Your_Version_groupBox_gridLayout = QtGui.QGridLayout(self.Your_Version_groupBox)
                self.Your_Version_groupBox_gridLayout.setObjectName("Your_Version_groupBox_gridLayout")
                self.Your_Version_label = QtGui.QLabel(self.Your_Version_groupBox)
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setWeight(75)
                font.setBold(True)
                self.Your_Version_label.setFont(font)
                self.Your_Version_label.setAlignment(QtCore.Qt.AlignCenter)
                self.Your_Version_label.setObjectName("Your_Version_label")
                self.Your_Version_groupBox_gridLayout.addWidget(self.Your_Version_label, 0, 0, 1, 1)
                self.sIBL_GUI_groupBox_gridLayout.addWidget(self.Your_Version_groupBox, 0, 1, 1, 1)
                self.Logo_horizontalLayout = QtGui.QHBoxLayout()
                self.Logo_horizontalLayout.setObjectName("Logo_horizontalLayout")
                spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Logo_horizontalLayout.addItem(spacerItem1)
                self.Logo_label = QtGui.QLabel(self.sIBL_GUI_groupBox)
                self.Logo_label.setPixmap(QtGui.QPixmap(":/sIBL_GUI FTP/Resources/sIBL_GUI_Small_Logo.png"))
                self.Logo_label.setObjectName("Logo_label")
                self.Logo_horizontalLayout.addWidget(self.Logo_label)
                spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Logo_horizontalLayout.addItem(spacerItem2)
                self.sIBL_GUI_groupBox_gridLayout.addLayout(self.Logo_horizontalLayout, 0, 2, 1, 1)
                self.Latest_Version_groupBox = QtGui.QGroupBox(self.sIBL_GUI_groupBox)
                self.Latest_Version_groupBox.setObjectName("Latest_Version_groupBox")
                self.Latest_Version_groupBox_gridLayout = QtGui.QGridLayout(self.Latest_Version_groupBox)
                self.Latest_Version_groupBox_gridLayout.setObjectName("Latest_Version_groupBox_gridLayout")
                self.Latest_Version_label = QtGui.QLabel(self.Latest_Version_groupBox)
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setWeight(75)
                font.setBold(True)
                self.Latest_Version_label.setFont(font)
                self.Latest_Version_label.setAlignment(QtCore.Qt.AlignCenter)
                self.Latest_Version_label.setObjectName("Latest_Version_label")
                self.Latest_Version_groupBox_gridLayout.addWidget(self.Latest_Version_label, 0, 0, 1, 1)
                self.sIBL_GUI_groupBox_gridLayout.addWidget(self.Latest_Version_groupBox, 0, 3, 1, 1)
                self.Change_Log_groupBox = QtGui.QGroupBox(self.sIBL_GUI_groupBox)
                self.Change_Log_groupBox.setObjectName("Change_Log_groupBox")
                self.Change_Log_gridLayout = QtGui.QGridLayout(self.Change_Log_groupBox)
                self.Change_Log_gridLayout.setObjectName("Change_Log_gridLayout")
                self.Change_Log_webView = QtWebKit.QWebView(self.Change_Log_groupBox)
                self.Change_Log_webView.setEnabled(True)
                self.Change_Log_webView.setUrl(QtCore.QUrl("about:blank"))
                self.Change_Log_webView.setObjectName("Change_Log_webView")
                self.Change_Log_gridLayout.addWidget(self.Change_Log_webView, 0, 0, 1, 1)
                self.sIBL_GUI_groupBox_gridLayout.addWidget(self.Change_Log_groupBox, 1, 0, 1, 4)
                self.Templates_groupBox = QtGui.QGroupBox(self.Releases_splitter)
                self.Templates_groupBox.setObjectName("Templates_groupBox")
                self.Templates_gridLayout = QtGui.QGridLayout(self.Templates_groupBox)
                self.Templates_gridLayout.setObjectName("Templates_gridLayout")
                self.Templates_tableWidget = QtGui.QTableWidget(self.Templates_groupBox)
                sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.Templates_tableWidget.sizePolicy().hasHeightForWidth())
                self.Templates_tableWidget.setSizePolicy(sizePolicy)
                self.Templates_tableWidget.setObjectName("Templates_tableWidget")
                self.Templates_tableWidget.setColumnCount(0)
                self.Templates_tableWidget.setRowCount(0)
                self.Templates_gridLayout.addWidget(self.Templates_tableWidget, 0, 0, 1, 2)
                self.sIBL_GUI_Updater_Form_gridLayout.addWidget(self.Releases_splitter, 2, 0, 1, 1)

                self.retranslateUi(sIBL_GUI_Updater_Form)
                QtCore.QMetaObject.connectSlotsByName(sIBL_GUI_Updater_Form)

        def retranslateUi(self, sIBL_GUI_Updater_Form):
                sIBL_GUI_Updater_Form.setWindowTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "sIBL_GUI Updater", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_Repository_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Open Repository", None, QtGui.QApplication.UnicodeUTF8))
                self.Get_Latest_Templates_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Get Latest Templates", None, QtGui.QApplication.UnicodeUTF8))
                self.Close_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
                self.Message_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Some New Releases Are Available !", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "sIBL_GUI - New Release", None, QtGui.QApplication.UnicodeUTF8))
                self.Your_Version_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Your Version", None, QtGui.QApplication.UnicodeUTF8))
                self.Latest_Version_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Latest Version", None, QtGui.QApplication.UnicodeUTF8))
                self.Change_Log_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "sIBL_GUI - Change Log", None, QtGui.QApplication.UnicodeUTF8))
                self.Templates_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI_Updater_Form", "Templates - New Releases / New Templates", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import sIBL_GUI_Updater_rc
import sIBL_GUI_Updater_rc
import sIBL_GUI_Updater_rc
