# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/sIBL_GUI.ui'
#
# Created: Sun Jun 28 23:54:37 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_sIBL_GUI(object):
        def setupUi(self, sIBL_GUI):
                sIBL_GUI.setObjectName("sIBL_GUI")
                sIBL_GUI.resize(658, 738)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/sIBL_GUI/Resources/Icon_Light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                sIBL_GUI.setWindowIcon(icon)
                sIBL_GUI.setDockNestingEnabled(True)
                sIBL_GUI.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks)
                self.sIBL_GUI_centralwidget = QtGui.QWidget(sIBL_GUI)
                self.sIBL_GUI_centralwidget.setObjectName("sIBL_GUI_centralwidget")
                self.sIBL_GUI_centralwidget_gridLayout = QtGui.QGridLayout(self.sIBL_GUI_centralwidget)
                self.sIBL_GUI_centralwidget_gridLayout.setObjectName("sIBL_GUI_centralwidget_gridLayout")
                self.Logo_label = QtGui.QLabel(self.sIBL_GUI_centralwidget)
                self.Logo_label.setPixmap(QtGui.QPixmap(":/sIBL_GUI/Resources/sIBL_GUI_Logo.png"))
                self.Logo_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.Logo_label.setObjectName("Logo_label")
                self.sIBL_GUI_centralwidget_gridLayout.addWidget(self.Logo_label, 0, 0, 1, 1)
                self.sIBL_GUI_tabWidget = QtGui.QTabWidget(self.sIBL_GUI_centralwidget)
                self.sIBL_GUI_tabWidget.setTabPosition(QtGui.QTabWidget.North)
                self.sIBL_GUI_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
                self.sIBL_GUI_tabWidget.setElideMode(QtCore.Qt.ElideNone)
                self.sIBL_GUI_tabWidget.setObjectName("sIBL_GUI_tabWidget")
                self.Collections_Browser_tab = QtGui.QWidget()
                self.Collections_Browser_tab.setObjectName("Collections_Browser_tab")
                self.Collections_Browser_tab_gridLayout = QtGui.QGridLayout(self.Collections_Browser_tab)
                self.Collections_Browser_tab_gridLayout.setObjectName("Collections_Browser_tab_gridLayout")
                self.Filters_groupBox = QtGui.QGroupBox(self.Collections_Browser_tab)
                self.Filters_groupBox.setObjectName("Filters_groupBox")
                self.Filters_groupBox_gridLayout = QtGui.QGridLayout(self.Filters_groupBox)
                self.Filters_groupBox_gridLayout.setObjectName("Filters_groupBox_gridLayout")
                self.Collections_label = QtGui.QLabel(self.Filters_groupBox)
                self.Collections_label.setObjectName("Collections_label")
                self.Filters_groupBox_gridLayout.addWidget(self.Collections_label, 0, 0, 1, 1)
                self.Collections_comboBox = QtGui.QComboBox(self.Filters_groupBox)
                self.Collections_comboBox.setObjectName("Collections_comboBox")
                self.Filters_groupBox_gridLayout.addWidget(self.Collections_comboBox, 0, 1, 1, 1)
                self.Authors_label = QtGui.QLabel(self.Filters_groupBox)
                self.Authors_label.setObjectName("Authors_label")
                self.Filters_groupBox_gridLayout.addWidget(self.Authors_label, 0, 2, 1, 1)
                self.Authors_comboBox = QtGui.QComboBox(self.Filters_groupBox)
                self.Authors_comboBox.setObjectName("Authors_comboBox")
                self.Filters_groupBox_gridLayout.addWidget(self.Authors_comboBox, 0, 3, 1, 1)
                self.Locations_label = QtGui.QLabel(self.Filters_groupBox)
                self.Locations_label.setObjectName("Locations_label")
                self.Filters_groupBox_gridLayout.addWidget(self.Locations_label, 0, 4, 1, 1)
                self.Locations_comboBox = QtGui.QComboBox(self.Filters_groupBox)
                self.Locations_comboBox.setObjectName("Locations_comboBox")
                self.Filters_groupBox_gridLayout.addWidget(self.Locations_comboBox, 0, 5, 1, 1)
                self.Collections_Browser_tab_gridLayout.addWidget(self.Filters_groupBox, 0, 0, 1, 1)
                self.Search_groupBox = QtGui.QGroupBox(self.Collections_Browser_tab)
                self.Search_groupBox.setObjectName("Search_groupBox")
                self.Search_groupBox_gridLayout = QtGui.QGridLayout(self.Search_groupBox)
                self.Search_groupBox_gridLayout.setObjectName("Search_groupBox_gridLayout")
                self.Search_lineEdit = QtGui.QLineEdit(self.Search_groupBox)
                self.Search_lineEdit.setObjectName("Search_lineEdit")
                self.Search_groupBox_gridLayout.addWidget(self.Search_lineEdit, 0, 0, 1, 1)
                self.Collections_Browser_tab_gridLayout.addWidget(self.Search_groupBox, 0, 1, 1, 1)
                self.Browser_GPS_Map_groupBox = QtGui.QGroupBox(self.Collections_Browser_tab)
                self.Browser_GPS_Map_groupBox.setObjectName("Browser_GPS_Map_groupBox")
                self.Collections_groupBox_gridLayout = QtGui.QGridLayout(self.Browser_GPS_Map_groupBox)
                self.Collections_groupBox_gridLayout.setObjectName("Collections_groupBox_gridLayout")
                self.Browser_GPS_Map_toolBox = QtGui.QToolBox(self.Browser_GPS_Map_groupBox)
                self.Browser_GPS_Map_toolBox.setObjectName("Browser_GPS_Map_toolBox")
                self.Browser_Page = QtGui.QWidget()
                self.Browser_Page.setGeometry(QtCore.QRect(0, 0, 596, 241))
                self.Browser_Page.setObjectName("Browser_Page")
                self.Browser_Page_gridLayout = QtGui.QGridLayout(self.Browser_Page)
                self.Browser_Page_gridLayout.setMargin(0)
                self.Browser_Page_gridLayout.setObjectName("Browser_Page_gridLayout")
                self.Collections_listWidget = QtGui.QListWidget(self.Browser_Page)
                self.Collections_listWidget.setFrameShape(QtGui.QFrame.Box)
                self.Collections_listWidget.setMovement(QtGui.QListView.Static)
                self.Collections_listWidget.setResizeMode(QtGui.QListView.Adjust)
                self.Collections_listWidget.setViewMode(QtGui.QListView.IconMode)
                self.Collections_listWidget.setWordWrap(True)
                self.Collections_listWidget.setObjectName("Collections_listWidget")
                self.Browser_Page_gridLayout.addWidget(self.Collections_listWidget, 0, 0, 1, 1)
                self.Browser_GPS_Map_toolBox.addItem(self.Browser_Page, "")
                self.GPS_Map_Page = QtGui.QWidget()
                self.GPS_Map_Page.setGeometry(QtCore.QRect(0, 0, 596, 241))
                self.GPS_Map_Page.setObjectName("GPS_Map_Page")
                self.GPS_Map_Page_gridLayout = QtGui.QGridLayout(self.GPS_Map_Page)
                self.GPS_Map_Page_gridLayout.setMargin(0)
                self.GPS_Map_Page_gridLayout.setObjectName("GPS_Map_Page_gridLayout")
                self.Browser_GPS_Map_toolBox.addItem(self.GPS_Map_Page, "")
                self.Collections_groupBox_gridLayout.addWidget(self.Browser_GPS_Map_toolBox, 0, 0, 1, 1)
                self.Collections_Browser_tab_gridLayout.addWidget(self.Browser_GPS_Map_groupBox, 1, 0, 1, 2)
                self.sIBL_GUI_tabWidget.addTab(self.Collections_Browser_tab, "")
                self.Import_tab = QtGui.QWidget()
                self.Import_tab.setEnabled(True)
                self.Import_tab.setObjectName("Import_tab")
                self.Import_tab_gridLayout = QtGui.QGridLayout(self.Import_tab)
                self.Import_tab_gridLayout.setObjectName("Import_tab_gridLayout")
                spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Import_tab_gridLayout.addItem(spacerItem, 0, 2, 1, 1)
                self.sIBL_groupBox = QtGui.QGroupBox(self.Import_tab)
                self.sIBL_groupBox.setMaximumSize(QtCore.QSize(202, 16777215))
                self.sIBL_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.sIBL_groupBox.setFlat(True)
                self.sIBL_groupBox.setObjectName("sIBL_groupBox")
                self.Preview_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_groupBox)
                self.Preview_groupBox_gridLayout.setMargin(0)
                self.Preview_groupBox_gridLayout.setObjectName("Preview_groupBox_gridLayout")
                self.sIBL_Infos_groupBox = QtGui.QGroupBox(self.sIBL_groupBox)
                self.sIBL_Infos_groupBox.setObjectName("sIBL_Infos_groupBox")
                self.Infos_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_Infos_groupBox)
                self.Infos_groupBox_gridLayout.setMargin(0)
                self.Infos_groupBox_gridLayout.setObjectName("Infos_groupBox_gridLayout")
                self.sIBL_Infos_scrollArea = QtGui.QScrollArea(self.sIBL_Infos_groupBox)
                self.sIBL_Infos_scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
                self.sIBL_Infos_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.sIBL_Infos_scrollArea.setWidgetResizable(True)
                self.sIBL_Infos_scrollArea.setObjectName("sIBL_Infos_scrollArea")
                self.sIBL_Infos_scrollAreaWidgetContents = QtGui.QWidget(self.sIBL_Infos_scrollArea)
                self.sIBL_Infos_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 130, 215))
                self.sIBL_Infos_scrollAreaWidgetContents.setObjectName("sIBL_Infos_scrollAreaWidgetContents")
                self.sIBL_Infos_scrollAreaWidgetContents_gridLayout = QtGui.QGridLayout(self.sIBL_Infos_scrollAreaWidgetContents)
                self.sIBL_Infos_scrollAreaWidgetContents_gridLayout.setObjectName("sIBL_Infos_scrollAreaWidgetContents_gridLayout")
                self.Location_groupBox = QtGui.QGroupBox(self.sIBL_Infos_scrollAreaWidgetContents)
                self.Location_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Location_groupBox.setFlat(True)
                self.Location_groupBox.setObjectName("Location_groupBox")
                self.Location_groupBox_gridLayout = QtGui.QGridLayout(self.Location_groupBox)
                self.Location_groupBox_gridLayout.setMargin(0)
                self.Location_groupBox_gridLayout.setObjectName("Location_groupBox_gridLayout")
                self.sIBL_Location_Set_label = QtGui.QLabel(self.Location_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.sIBL_Location_Set_label.setFont(font)
                self.sIBL_Location_Set_label.setMargin(4)
                self.sIBL_Location_Set_label.setObjectName("sIBL_Location_Set_label")
                self.Location_groupBox_gridLayout.addWidget(self.sIBL_Location_Set_label, 0, 0, 1, 1)
                self.sIBL_Infos_scrollAreaWidgetContents_gridLayout.addWidget(self.Location_groupBox, 1, 0, 1, 1)
                self.sIBL_Author_groupBox = QtGui.QGroupBox(self.sIBL_Infos_scrollAreaWidgetContents)
                self.sIBL_Author_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.sIBL_Author_groupBox.setFlat(True)
                self.sIBL_Author_groupBox.setObjectName("sIBL_Author_groupBox")
                self.sIBL_Author_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_Author_groupBox)
                self.sIBL_Author_groupBox_gridLayout.setMargin(0)
                self.sIBL_Author_groupBox_gridLayout.setObjectName("sIBL_Author_groupBox_gridLayout")
                self.sIBL_Author_Set_label = QtGui.QLabel(self.sIBL_Author_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.sIBL_Author_Set_label.setFont(font)
                self.sIBL_Author_Set_label.setMargin(4)
                self.sIBL_Author_Set_label.setOpenExternalLinks(True)
                self.sIBL_Author_Set_label.setObjectName("sIBL_Author_Set_label")
                self.sIBL_Author_groupBox_gridLayout.addWidget(self.sIBL_Author_Set_label, 0, 0, 1, 1)
                self.sIBL_Infos_scrollAreaWidgetContents_gridLayout.addWidget(self.sIBL_Author_groupBox, 2, 0, 1, 1)
                self.Shot_Date_groupBox = QtGui.QGroupBox(self.sIBL_Infos_scrollAreaWidgetContents)
                self.Shot_Date_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Shot_Date_groupBox.setFlat(True)
                self.Shot_Date_groupBox.setObjectName("Shot_Date_groupBox")
                self.Shot_Date_groupBox_gridLayout = QtGui.QGridLayout(self.Shot_Date_groupBox)
                self.Shot_Date_groupBox_gridLayout.setMargin(0)
                self.Shot_Date_groupBox_gridLayout.setObjectName("Shot_Date_groupBox_gridLayout")
                self.sIBL_Date_Set_label = QtGui.QLabel(self.Shot_Date_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.sIBL_Date_Set_label.setFont(font)
                self.sIBL_Date_Set_label.setMargin(4)
                self.sIBL_Date_Set_label.setObjectName("sIBL_Date_Set_label")
                self.Shot_Date_groupBox_gridLayout.addWidget(self.sIBL_Date_Set_label, 0, 0, 1, 1)
                self.sIBL_Infos_scrollAreaWidgetContents_gridLayout.addWidget(self.Shot_Date_groupBox, 5, 0, 1, 1)
                self.Comment_groupBox = QtGui.QGroupBox(self.sIBL_Infos_scrollAreaWidgetContents)
                self.Comment_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Comment_groupBox.setFlat(True)
                self.Comment_groupBox.setObjectName("Comment_groupBox")
                self.Comment_groupBox_gridLayout = QtGui.QGridLayout(self.Comment_groupBox)
                self.Comment_groupBox_gridLayout.setMargin(0)
                self.Comment_groupBox_gridLayout.setObjectName("Comment_groupBox_gridLayout")
                self.Comment_textEdit = QtGui.QTextEdit(self.Comment_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.Comment_textEdit.setFont(font)
                self.Comment_textEdit.setFrameShape(QtGui.QFrame.NoFrame)
                self.Comment_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.Comment_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.Comment_textEdit.setUndoRedoEnabled(False)
                self.Comment_textEdit.setReadOnly(True)
                self.Comment_textEdit.setObjectName("Comment_textEdit")
                self.Comment_groupBox_gridLayout.addWidget(self.Comment_textEdit, 0, 0, 1, 1)
                self.sIBL_Infos_scrollAreaWidgetContents_gridLayout.addWidget(self.Comment_groupBox, 6, 0, 1, 1)
                self.sIBL_Infos_scrollArea.setWidget(self.sIBL_Infos_scrollAreaWidgetContents)
                self.Infos_groupBox_gridLayout.addWidget(self.sIBL_Infos_scrollArea, 0, 0, 1, 1)
                self.Preview_groupBox_gridLayout.addWidget(self.sIBL_Infos_groupBox, 1, 0, 1, 1)
                self.sIBL_Set_groupBox = QtGui.QGroupBox(self.sIBL_groupBox)
                self.sIBL_Set_groupBox.setObjectName("sIBL_Set_groupBox")
                self.sIBL_Set_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_Set_groupBox)
                self.sIBL_Set_groupBox_gridLayout.setObjectName("sIBL_Set_groupBox_gridLayout")
                self.Preview_label = QtGui.QLabel(self.sIBL_Set_groupBox)
                self.Preview_label.setPixmap(QtGui.QPixmap(":/sIBL_GUI/Resources/Icon_Light.png"))
                self.Preview_label.setAlignment(QtCore.Qt.AlignCenter)
                self.Preview_label.setObjectName("Preview_label")
                self.sIBL_Set_groupBox_gridLayout.addWidget(self.Preview_label, 0, 0, 1, 1)
                self.Preview_groupBox_gridLayout.addWidget(self.sIBL_Set_groupBox, 0, 0, 1, 1)
                self.sIBL_Options_groupBox = QtGui.QGroupBox(self.sIBL_groupBox)
                self.sIBL_Options_groupBox.setObjectName("sIBL_Options_groupBox")
                self.sIBL_Options_gridLayout = QtGui.QGridLayout(self.sIBL_Options_groupBox)
                self.sIBL_Options_gridLayout.setObjectName("sIBL_Options_gridLayout")
                self.Edit_In_sIBL_Edit_pushButton = QtGui.QPushButton(self.sIBL_Options_groupBox)
                self.Edit_In_sIBL_Edit_pushButton.setObjectName("Edit_In_sIBL_Edit_pushButton")
                self.sIBL_Options_gridLayout.addWidget(self.Edit_In_sIBL_Edit_pushButton, 0, 0, 1, 1)
                self.Refresh_sIBL_File_pushButton = QtGui.QPushButton(self.sIBL_Options_groupBox)
                self.Refresh_sIBL_File_pushButton.setObjectName("Refresh_sIBL_File_pushButton")
                self.sIBL_Options_gridLayout.addWidget(self.Refresh_sIBL_File_pushButton, 1, 0, 1, 1)
                self.Open_sIBL_Folder_pushButton = QtGui.QPushButton(self.sIBL_Options_groupBox)
                self.Open_sIBL_Folder_pushButton.setObjectName("Open_sIBL_Folder_pushButton")
                self.sIBL_Options_gridLayout.addWidget(self.Open_sIBL_Folder_pushButton, 2, 0, 1, 1)
                self.Preview_groupBox_gridLayout.addWidget(self.sIBL_Options_groupBox, 2, 0, 1, 1)
                self.Import_tab_gridLayout.addWidget(self.sIBL_groupBox, 0, 1, 1, 1)
                self.Template_groupBox = QtGui.QGroupBox(self.Import_tab)
                self.Template_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Template_groupBox.setFlat(True)
                self.Template_groupBox.setObjectName("Template_groupBox")
                self.Template_groupBox_gridLayout = QtGui.QGridLayout(self.Template_groupBox)
                self.Template_groupBox_gridLayout.setMargin(0)
                self.Template_groupBox_gridLayout.setObjectName("Template_groupBox_gridLayout")
                self.Template_Infos_groupBox = QtGui.QGroupBox(self.Template_groupBox)
                self.Template_Infos_groupBox.setObjectName("Template_Infos_groupBox")
                self.Template_Infos_groupBox_gridLayout = QtGui.QGridLayout(self.Template_Infos_groupBox)
                self.Template_Infos_groupBox_gridLayout.setMargin(0)
                self.Template_Infos_groupBox_gridLayout.setObjectName("Template_Infos_groupBox_gridLayout")
                self.Template_scrollArea = QtGui.QScrollArea(self.Template_Infos_groupBox)
                self.Template_scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
                self.Template_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.Template_scrollArea.setWidgetResizable(True)
                self.Template_scrollArea.setObjectName("Template_scrollArea")
                self.Template_scrollAreaWidgetContents = QtGui.QWidget(self.Template_scrollArea)
                self.Template_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -94, 134, 243))
                self.Template_scrollAreaWidgetContents.setObjectName("Template_scrollAreaWidgetContents")
                self.Template_scrollAreaWidgetContents_gridLayout = QtGui.QGridLayout(self.Template_scrollAreaWidgetContents)
                self.Template_scrollAreaWidgetContents_gridLayout.setObjectName("Template_scrollAreaWidgetContents_gridLayout")
                self.Release_groupBox = QtGui.QGroupBox(self.Template_scrollAreaWidgetContents)
                self.Release_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Release_groupBox.setFlat(True)
                self.Release_groupBox.setObjectName("Release_groupBox")
                self.Release_groupBox_gridLayout = QtGui.QGridLayout(self.Release_groupBox)
                self.Release_groupBox_gridLayout.setMargin(0)
                self.Release_groupBox_gridLayout.setObjectName("Release_groupBox_gridLayout")
                self.Release_Set_label = QtGui.QLabel(self.Release_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.Release_Set_label.setFont(font)
                self.Release_Set_label.setMargin(4)
                self.Release_Set_label.setObjectName("Release_Set_label")
                self.Release_groupBox_gridLayout.addWidget(self.Release_Set_label, 0, 0, 1, 1)
                self.Template_scrollAreaWidgetContents_gridLayout.addWidget(self.Release_groupBox, 0, 0, 1, 1)
                self.Software_Set_groupBox = QtGui.QGroupBox(self.Template_scrollAreaWidgetContents)
                self.Software_Set_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Software_Set_groupBox.setFlat(True)
                self.Software_Set_groupBox.setObjectName("Software_Set_groupBox")
                self.Software_Set_groupBox_gridLayout = QtGui.QGridLayout(self.Software_Set_groupBox)
                self.Software_Set_groupBox_gridLayout.setMargin(0)
                self.Software_Set_groupBox_gridLayout.setObjectName("Software_Set_groupBox_gridLayout")
                self.Software_Version_label = QtGui.QLabel(self.Software_Set_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.Software_Version_label.setFont(font)
                self.Software_Version_label.setMargin(4)
                self.Software_Version_label.setObjectName("Software_Version_label")
                self.Software_Set_groupBox_gridLayout.addWidget(self.Software_Version_label, 0, 0, 1, 1)
                self.Template_scrollAreaWidgetContents_gridLayout.addWidget(self.Software_Set_groupBox, 1, 0, 1, 1)
                self.Template_Author_groupBox = QtGui.QGroupBox(self.Template_scrollAreaWidgetContents)
                self.Template_Author_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Template_Author_groupBox.setFlat(True)
                self.Template_Author_groupBox.setObjectName("Template_Author_groupBox")
                self.Template_Author_groupBox_gridLayout = QtGui.QGridLayout(self.Template_Author_groupBox)
                self.Template_Author_groupBox_gridLayout.setMargin(0)
                self.Template_Author_groupBox_gridLayout.setObjectName("Template_Author_groupBox_gridLayout")
                self.Template_Author_Set_label = QtGui.QLabel(self.Template_Author_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.Template_Author_Set_label.setFont(font)
                self.Template_Author_Set_label.setMargin(4)
                self.Template_Author_Set_label.setOpenExternalLinks(True)
                self.Template_Author_Set_label.setObjectName("Template_Author_Set_label")
                self.Template_Author_groupBox_gridLayout.addWidget(self.Template_Author_Set_label, 0, 0, 1, 1)
                self.Template_scrollAreaWidgetContents_gridLayout.addWidget(self.Template_Author_groupBox, 2, 0, 1, 1)
                self.Template_Loader_Script_groupBox = QtGui.QGroupBox(self.Template_scrollAreaWidgetContents)
                self.Template_Loader_Script_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Template_Loader_Script_groupBox.setFlat(True)
                self.Template_Loader_Script_groupBox.setObjectName("Template_Loader_Script_groupBox")
                self.Template_Loader_Script_groupBox_gridLayout = QtGui.QGridLayout(self.Template_Loader_Script_groupBox)
                self.Template_Loader_Script_groupBox_gridLayout.setMargin(0)
                self.Template_Loader_Script_groupBox_gridLayout.setObjectName("Template_Loader_Script_groupBox_gridLayout")
                self.Loader_Script_Set_label = QtGui.QLabel(self.Template_Loader_Script_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.Loader_Script_Set_label.setFont(font)
                self.Loader_Script_Set_label.setMargin(4)
                self.Loader_Script_Set_label.setObjectName("Loader_Script_Set_label")
                self.Template_Loader_Script_groupBox_gridLayout.addWidget(self.Loader_Script_Set_label, 0, 0, 1, 1)
                self.Template_scrollAreaWidgetContents_gridLayout.addWidget(self.Template_Loader_Script_groupBox, 3, 0, 1, 1)
                self.Template_Comment_groupBox = QtGui.QGroupBox(self.Template_scrollAreaWidgetContents)
                self.Template_Comment_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Template_Comment_groupBox.setFlat(True)
                self.Template_Comment_groupBox.setObjectName("Template_Comment_groupBox")
                self.Template_Comment_groupBox_gridLayout = QtGui.QGridLayout(self.Template_Comment_groupBox)
                self.Template_Comment_groupBox_gridLayout.setMargin(0)
                self.Template_Comment_groupBox_gridLayout.setObjectName("Template_Comment_groupBox_gridLayout")
                self.Template_Comment_textEdit = QtGui.QTextEdit(self.Template_Comment_groupBox)
                font = QtGui.QFont()
                font.setItalic(True)
                self.Template_Comment_textEdit.setFont(font)
                self.Template_Comment_textEdit.setFrameShape(QtGui.QFrame.NoFrame)
                self.Template_Comment_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.Template_Comment_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.Template_Comment_textEdit.setUndoRedoEnabled(False)
                self.Template_Comment_textEdit.setReadOnly(True)
                self.Template_Comment_textEdit.setObjectName("Template_Comment_textEdit")
                self.Template_Comment_groupBox_gridLayout.addWidget(self.Template_Comment_textEdit, 0, 0, 1, 1)
                self.Template_scrollAreaWidgetContents_gridLayout.addWidget(self.Template_Comment_groupBox, 4, 0, 1, 1)
                self.Template_scrollArea.setWidget(self.Template_scrollAreaWidgetContents)
                self.Template_Infos_groupBox_gridLayout.addWidget(self.Template_scrollArea, 0, 0, 1, 1)
                self.Template_groupBox_gridLayout.addWidget(self.Template_Infos_groupBox, 0, 2, 5, 1)
                self.Options_groupBox = QtGui.QGroupBox(self.Template_groupBox)
                sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.Options_groupBox.sizePolicy().hasHeightForWidth())
                self.Options_groupBox.setSizePolicy(sizePolicy)
                self.Options_groupBox.setObjectName("Options_groupBox")
                self.Options_gridLayout = QtGui.QGridLayout(self.Options_groupBox)
                self.Options_gridLayout.setObjectName("Options_gridLayout")
                self.Options_toolBox = QtGui.QToolBox(self.Options_groupBox)
                self.Options_toolBox.setObjectName("Options_toolBox")
                self.Common_Attributes_page = QtGui.QWidget()
                self.Common_Attributes_page.setGeometry(QtCore.QRect(0, 0, 256, 162))
                self.Common_Attributes_page.setObjectName("Common_Attributes_page")
                self.Common_Attributes_page_gridLayout = QtGui.QGridLayout(self.Common_Attributes_page)
                self.Common_Attributes_page_gridLayout.setMargin(0)
                self.Common_Attributes_page_gridLayout.setObjectName("Common_Attributes_page_gridLayout")
                self.Common_Attributes_tableWidget = QtGui.QTableWidget(self.Common_Attributes_page)
                self.Common_Attributes_tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
                self.Common_Attributes_tableWidget.setCornerButtonEnabled(False)
                self.Common_Attributes_tableWidget.setObjectName("Common_Attributes_tableWidget")
                self.Common_Attributes_tableWidget.setColumnCount(0)
                self.Common_Attributes_tableWidget.setRowCount(0)
                self.Common_Attributes_page_gridLayout.addWidget(self.Common_Attributes_tableWidget, 0, 0, 1, 1)
                self.Options_toolBox.addItem(self.Common_Attributes_page, "")
                self.Additional_Attributes_page = QtGui.QWidget()
                self.Additional_Attributes_page.setGeometry(QtCore.QRect(0, 0, 96, 61))
                self.Additional_Attributes_page.setObjectName("Additional_Attributes_page")
                self.Additional_Attributes_page_gridLayout = QtGui.QGridLayout(self.Additional_Attributes_page)
                self.Additional_Attributes_page_gridLayout.setMargin(0)
                self.Additional_Attributes_page_gridLayout.setObjectName("Additional_Attributes_page_gridLayout")
                self.Additional_Attributes_tableWidget = QtGui.QTableWidget(self.Additional_Attributes_page)
                self.Additional_Attributes_tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
                self.Additional_Attributes_tableWidget.setCornerButtonEnabled(False)
                self.Additional_Attributes_tableWidget.setObjectName("Additional_Attributes_tableWidget")
                self.Additional_Attributes_tableWidget.setColumnCount(0)
                self.Additional_Attributes_tableWidget.setRowCount(0)
                self.Additional_Attributes_page_gridLayout.addWidget(self.Additional_Attributes_tableWidget, 0, 0, 1, 1)
                self.Options_toolBox.addItem(self.Additional_Attributes_page, "")
                self.Options_gridLayout.addWidget(self.Options_toolBox, 0, 0, 1, 2)
                self.Template_groupBox_gridLayout.addWidget(self.Options_groupBox, 1, 0, 7, 1)
                self.Loader_Script_groupBox = QtGui.QGroupBox(self.Template_groupBox)
                self.Loader_Script_groupBox.setObjectName("Loader_Script_groupBox")
                self.Loader_Script_groupBox_gridLayout = QtGui.QGridLayout(self.Loader_Script_groupBox)
                self.Loader_Script_groupBox_gridLayout.setObjectName("Loader_Script_groupBox_gridLayout")
                self.Output_Loader_Script_pushButton = QtGui.QPushButton(self.Loader_Script_groupBox)
                self.Output_Loader_Script_pushButton.setMinimumSize(QtCore.QSize(0, 24))
                self.Output_Loader_Script_pushButton.setObjectName("Output_Loader_Script_pushButton")
                self.Loader_Script_groupBox_gridLayout.addWidget(self.Output_Loader_Script_pushButton, 2, 0, 1, 1)
                self.Open_Output_Folder_pushButton = QtGui.QPushButton(self.Loader_Script_groupBox)
                self.Open_Output_Folder_pushButton.setEnabled(True)
                self.Open_Output_Folder_pushButton.setMinimumSize(QtCore.QSize(0, 24))
                self.Open_Output_Folder_pushButton.setObjectName("Open_Output_Folder_pushButton")
                self.Loader_Script_groupBox_gridLayout.addWidget(self.Open_Output_Folder_pushButton, 3, 0, 1, 1)
                self.Template_groupBox_gridLayout.addWidget(self.Loader_Script_groupBox, 5, 2, 2, 1)
                self.Software_Templates_groupBox = QtGui.QGroupBox(self.Template_groupBox)
                self.Software_Templates_groupBox.setObjectName("Software_Templates_groupBox")
                self.Software_Templates_groupBox_gridLayout = QtGui.QGridLayout(self.Software_Templates_groupBox)
                self.Software_Templates_groupBox_gridLayout.setObjectName("Software_Templates_groupBox_gridLayout")
                self.Edit_Current_Template_pushButton = QtGui.QPushButton(self.Software_Templates_groupBox)
                self.Edit_Current_Template_pushButton.setEnabled(True)
                self.Edit_Current_Template_pushButton.setObjectName("Edit_Current_Template_pushButton")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Edit_Current_Template_pushButton, 5, 0, 1, 1)
                self.Open_Templates_Folder_pushButton = QtGui.QPushButton(self.Software_Templates_groupBox)
                self.Open_Templates_Folder_pushButton.setEnabled(True)
                self.Open_Templates_Folder_pushButton.setObjectName("Open_Templates_Folder_pushButton")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Open_Templates_Folder_pushButton, 5, 1, 1, 1)
                self.Template_label = QtGui.QLabel(self.Software_Templates_groupBox)
                self.Template_label.setObjectName("Template_label")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Template_label, 3, 0, 1, 1)
                self.Template_comboBox = QtGui.QComboBox(self.Software_Templates_groupBox)
                self.Template_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
                self.Template_comboBox.setObjectName("Template_comboBox")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Template_comboBox, 3, 1, 1, 1)
                self.Software_label = QtGui.QLabel(self.Software_Templates_groupBox)
                self.Software_label.setObjectName("Software_label")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Software_label, 2, 0, 1, 1)
                self.Software_comboBox = QtGui.QComboBox(self.Software_Templates_groupBox)
                self.Software_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
                self.Software_comboBox.setObjectName("Software_comboBox")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Software_comboBox, 2, 1, 1, 1)
                self.Templates_line = QtGui.QFrame(self.Software_Templates_groupBox)
                self.Templates_line.setFrameShape(QtGui.QFrame.HLine)
                self.Templates_line.setFrameShadow(QtGui.QFrame.Sunken)
                self.Templates_line.setObjectName("Templates_line")
                self.Software_Templates_groupBox_gridLayout.addWidget(self.Templates_line, 4, 0, 1, 2)
                self.Template_groupBox_gridLayout.addWidget(self.Software_Templates_groupBox, 0, 0, 1, 1)
                spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Template_groupBox_gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
                self.Remote_Connection_groupBox = QtGui.QGroupBox(self.Template_groupBox)
                self.Remote_Connection_groupBox.setObjectName("Remote_Connection_groupBox")
                self.Socket_Connection_gridLayout = QtGui.QGridLayout(self.Remote_Connection_groupBox)
                self.Socket_Connection_gridLayout.setObjectName("Socket_Connection_gridLayout")
                self.Send_To_Software_pushButton = QtGui.QPushButton(self.Remote_Connection_groupBox)
                self.Send_To_Software_pushButton.setMinimumSize(QtCore.QSize(0, 24))
                self.Send_To_Software_pushButton.setObjectName("Send_To_Software_pushButton")
                self.Socket_Connection_gridLayout.addWidget(self.Send_To_Software_pushButton, 0, 0, 1, 1)
                self.Remote_Connection_Options_frame = QtGui.QFrame(self.Remote_Connection_groupBox)
                self.Remote_Connection_Options_frame.setObjectName("Remote_Connection_Options_frame")
                self.Remote_Connection_Options_frame_gridLayout = QtGui.QGridLayout(self.Remote_Connection_Options_frame)
                self.Remote_Connection_Options_frame_gridLayout.setMargin(0)
                self.Remote_Connection_Options_frame_gridLayout.setObjectName("Remote_Connection_Options_frame_gridLayout")
                self.Port_label = QtGui.QLabel(self.Remote_Connection_Options_frame)
                self.Port_label.setObjectName("Port_label")
                self.Remote_Connection_Options_frame_gridLayout.addWidget(self.Port_label, 1, 0, 1, 1)
                self.Software_Port_spinBox = QtGui.QSpinBox(self.Remote_Connection_Options_frame)
                self.Software_Port_spinBox.setMinimumSize(QtCore.QSize(0, 20))
                self.Software_Port_spinBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Software_Port_spinBox.setMaximum(65535)
                self.Software_Port_spinBox.setProperty("value", QtCore.QVariant(2048))
                self.Software_Port_spinBox.setObjectName("Software_Port_spinBox")
                self.Remote_Connection_Options_frame_gridLayout.addWidget(self.Software_Port_spinBox, 1, 1, 1, 1)
                self.Address_label = QtGui.QLabel(self.Remote_Connection_Options_frame)
                self.Address_label.setObjectName("Address_label")
                self.Remote_Connection_Options_frame_gridLayout.addWidget(self.Address_label, 0, 0, 1, 1)
                self.Address_lineEdit = QtGui.QLineEdit(self.Remote_Connection_Options_frame)
                self.Address_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
                self.Address_lineEdit.setObjectName("Address_lineEdit")
                self.Remote_Connection_Options_frame_gridLayout.addWidget(self.Address_lineEdit, 0, 1, 1, 1)
                self.Socket_Connection_gridLayout.addWidget(self.Remote_Connection_Options_frame, 1, 0, 1, 1)
                self.Template_groupBox_gridLayout.addWidget(self.Remote_Connection_groupBox, 7, 2, 1, 1)
                self.Import_tab_gridLayout.addWidget(self.Template_groupBox, 0, 3, 1, 1)
                spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Import_tab_gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
                spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Import_tab_gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
                self.sIBL_GUI_tabWidget.addTab(self.Import_tab, "")
                self.Preferences_tab = QtGui.QWidget()
                self.Preferences_tab.setObjectName("Preferences_tab")
                self.Preferences_tab_gridLayout = QtGui.QGridLayout(self.Preferences_tab)
                self.Preferences_tab_gridLayout.setObjectName("Preferences_tab_gridLayout")
                self.Preferences_toolBox = QtGui.QToolBox(self.Preferences_tab)
                self.Preferences_toolBox.setObjectName("Preferences_toolBox")
                self.Overall_Settings_page = QtGui.QWidget()
                self.Overall_Settings_page.setGeometry(QtCore.QRect(0, 0, 618, 311))
                self.Overall_Settings_page.setObjectName("Overall_Settings_page")
                self.Overall_Settings_page_gridLayout = QtGui.QGridLayout(self.Overall_Settings_page)
                self.Overall_Settings_page_gridLayout.setContentsMargins(-1, 0, -1, 0)
                self.Overall_Settings_page_gridLayout.setObjectName("Overall_Settings_page_gridLayout")
                self.Custom_Executables_groupBox = QtGui.QGroupBox(self.Overall_Settings_page)
                self.Custom_Executables_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Custom_Executables_groupBox.setFlat(True)
                self.Custom_Executables_groupBox.setObjectName("Custom_Executables_groupBox")
                self.Custom_Executables_groupBox_gridLayout = QtGui.QGridLayout(self.Custom_Executables_groupBox)
                self.Custom_Executables_groupBox_gridLayout.setMargin(0)
                self.Custom_Executables_groupBox_gridLayout.setObjectName("Custom_Executables_groupBox_gridLayout")
                self.Custom_Text_Editor_Path_groupBox = QtGui.QGroupBox(self.Custom_Executables_groupBox)
                self.Custom_Text_Editor_Path_groupBox.setMaximumSize(QtCore.QSize(16777215, 64))
                self.Custom_Text_Editor_Path_groupBox.setObjectName("Custom_Text_Editor_Path_groupBox")
                self.Custom_Text_Editor_Path_groupBox_gridLayout = QtGui.QGridLayout(self.Custom_Text_Editor_Path_groupBox)
                self.Custom_Text_Editor_Path_groupBox_gridLayout.setObjectName("Custom_Text_Editor_Path_groupBox_gridLayout")
                self.Custom_Text_Editor_Path_lineEdit = QtGui.QLineEdit(self.Custom_Text_Editor_Path_groupBox)
                self.Custom_Text_Editor_Path_lineEdit.setObjectName("Custom_Text_Editor_Path_lineEdit")
                self.Custom_Text_Editor_Path_groupBox_gridLayout.addWidget(self.Custom_Text_Editor_Path_lineEdit, 0, 0, 1, 1)
                self.Custom_Text_Editor_Path_toolButton = QtGui.QToolButton(self.Custom_Text_Editor_Path_groupBox)
                self.Custom_Text_Editor_Path_toolButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
                self.Custom_Text_Editor_Path_toolButton.setObjectName("Custom_Text_Editor_Path_toolButton")
                self.Custom_Text_Editor_Path_groupBox_gridLayout.addWidget(self.Custom_Text_Editor_Path_toolButton, 0, 1, 1, 1)
                self.Custom_Executables_groupBox_gridLayout.addWidget(self.Custom_Text_Editor_Path_groupBox, 0, 0, 1, 1)
                self.Custom_File_Browser_Path_groupBox = QtGui.QGroupBox(self.Custom_Executables_groupBox)
                self.Custom_File_Browser_Path_groupBox.setMaximumSize(QtCore.QSize(16777215, 64))
                self.Custom_File_Browser_Path_groupBox.setObjectName("Custom_File_Browser_Path_groupBox")
                self.Custom_File_Browser_Path_gridLayout = QtGui.QGridLayout(self.Custom_File_Browser_Path_groupBox)
                self.Custom_File_Browser_Path_gridLayout.setObjectName("Custom_File_Browser_Path_gridLayout")
                self.Custom_File_Browser_Path_lineEdit = QtGui.QLineEdit(self.Custom_File_Browser_Path_groupBox)
                self.Custom_File_Browser_Path_lineEdit.setObjectName("Custom_File_Browser_Path_lineEdit")
                self.Custom_File_Browser_Path_gridLayout.addWidget(self.Custom_File_Browser_Path_lineEdit, 0, 0, 1, 1)
                self.Custom_File_Browser_Path_toolButton = QtGui.QToolButton(self.Custom_File_Browser_Path_groupBox)
                self.Custom_File_Browser_Path_toolButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
                self.Custom_File_Browser_Path_toolButton.setObjectName("Custom_File_Browser_Path_toolButton")
                self.Custom_File_Browser_Path_gridLayout.addWidget(self.Custom_File_Browser_Path_toolButton, 0, 1, 1, 1)
                self.Custom_Executables_groupBox_gridLayout.addWidget(self.Custom_File_Browser_Path_groupBox, 0, 1, 1, 1)
                self.Templates_Setting_groupBox = QtGui.QGroupBox(self.Custom_Executables_groupBox)
                self.Templates_Setting_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Templates_Setting_groupBox.setFlat(True)
                self.Templates_Setting_groupBox.setObjectName("Templates_Setting_groupBox")
                self.Templates_Setting_groupBox_gridLayout = QtGui.QGridLayout(self.Templates_Setting_groupBox)
                self.Templates_Setting_groupBox_gridLayout.setMargin(0)
                self.Templates_Setting_groupBox_gridLayout.setObjectName("Templates_Setting_groupBox_gridLayout")
                self.Templates_Path_groupBox = QtGui.QGroupBox(self.Templates_Setting_groupBox)
                self.Templates_Path_groupBox.setMaximumSize(QtCore.QSize(16777215, 64))
                self.Templates_Path_groupBox.setObjectName("Templates_Path_groupBox")
                self.Templates_Path_groupBox_gridLayout = QtGui.QGridLayout(self.Templates_Path_groupBox)
                self.Templates_Path_groupBox_gridLayout.setObjectName("Templates_Path_groupBox_gridLayout")
                self.Templates_Path_lineEdit = QtGui.QLineEdit(self.Templates_Path_groupBox)
                self.Templates_Path_lineEdit.setObjectName("Templates_Path_lineEdit")
                self.Templates_Path_groupBox_gridLayout.addWidget(self.Templates_Path_lineEdit, 0, 0, 1, 1)
                self.Templates_toolButton = QtGui.QToolButton(self.Templates_Path_groupBox)
                self.Templates_toolButton.setObjectName("Templates_toolButton")
                self.Templates_Path_groupBox_gridLayout.addWidget(self.Templates_toolButton, 0, 1, 1, 1)
                self.Templates_Setting_groupBox_gridLayout.addWidget(self.Templates_Path_groupBox, 0, 0, 1, 1)
                self.Custom_Executables_groupBox_gridLayout.addWidget(self.Templates_Setting_groupBox, 1, 1, 1, 1)
                self.Help_Files_Settings_groupBox = QtGui.QGroupBox(self.Custom_Executables_groupBox)
                self.Help_Files_Settings_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Help_Files_Settings_groupBox.setFlat(True)
                self.Help_Files_Settings_groupBox.setObjectName("Help_Files_Settings_groupBox")
                self.Help_Files_Settings_groupBox_gridLayout = QtGui.QGridLayout(self.Help_Files_Settings_groupBox)
                self.Help_Files_Settings_groupBox_gridLayout.setMargin(0)
                self.Help_Files_Settings_groupBox_gridLayout.setObjectName("Help_Files_Settings_groupBox_gridLayout")
                self.Help_Files_Settings_Path_groupBox = QtGui.QGroupBox(self.Help_Files_Settings_groupBox)
                self.Help_Files_Settings_Path_groupBox.setMaximumSize(QtCore.QSize(16777215, 64))
                self.Help_Files_Settings_Path_groupBox.setObjectName("Help_Files_Settings_Path_groupBox")
                self.Help_Files_Settings_Path_groupBox_gridLayout = QtGui.QGridLayout(self.Help_Files_Settings_Path_groupBox)
                self.Help_Files_Settings_Path_groupBox_gridLayout.setObjectName("Help_Files_Settings_Path_groupBox_gridLayout")
                self.Help_Files_Path_lineEdit = QtGui.QLineEdit(self.Help_Files_Settings_Path_groupBox)
                self.Help_Files_Path_lineEdit.setObjectName("Help_Files_Path_lineEdit")
                self.Help_Files_Settings_Path_groupBox_gridLayout.addWidget(self.Help_Files_Path_lineEdit, 0, 0, 1, 1)
                self.Help_Files_toolButton = QtGui.QToolButton(self.Help_Files_Settings_Path_groupBox)
                self.Help_Files_toolButton.setObjectName("Help_Files_toolButton")
                self.Help_Files_Settings_Path_groupBox_gridLayout.addWidget(self.Help_Files_toolButton, 0, 1, 1, 1)
                self.Help_Files_Settings_groupBox_gridLayout.addWidget(self.Help_Files_Settings_Path_groupBox, 0, 0, 1, 1)
                self.Custom_Executables_groupBox_gridLayout.addWidget(self.Help_Files_Settings_groupBox, 1, 0, 1, 1)
                self.Overall_Settings_page_gridLayout.addWidget(self.Custom_Executables_groupBox, 1, 0, 1, 1)
                self.sIBL_Executables_groupBox = QtGui.QGroupBox(self.Overall_Settings_page)
                self.sIBL_Executables_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.sIBL_Executables_groupBox.setFlat(True)
                self.sIBL_Executables_groupBox.setObjectName("sIBL_Executables_groupBox")
                self.sIBL_Executables_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_Executables_groupBox)
                self.sIBL_Executables_groupBox_gridLayout.setMargin(0)
                self.sIBL_Executables_groupBox_gridLayout.setObjectName("sIBL_Executables_groupBox_gridLayout")
                self.sIBL_Framework_Path_groupBox = QtGui.QGroupBox(self.sIBL_Executables_groupBox)
                self.sIBL_Framework_Path_groupBox.setMaximumSize(QtCore.QSize(16777215, 64))
                self.sIBL_Framework_Path_groupBox.setObjectName("sIBL_Framework_Path_groupBox")
                self.sIBL_Framework_Path_groupBox_gridLayout = QtGui.QGridLayout(self.sIBL_Framework_Path_groupBox)
                self.sIBL_Framework_Path_groupBox_gridLayout.setObjectName("sIBL_Framework_Path_groupBox_gridLayout")
                self.sIBL_Framework_Path_lineEdit = QtGui.QLineEdit(self.sIBL_Framework_Path_groupBox)
                self.sIBL_Framework_Path_lineEdit.setObjectName("sIBL_Framework_Path_lineEdit")
                self.sIBL_Framework_Path_groupBox_gridLayout.addWidget(self.sIBL_Framework_Path_lineEdit, 0, 0, 1, 1)
                self.sIBL_Framework_Path_toolButton = QtGui.QToolButton(self.sIBL_Framework_Path_groupBox)
                self.sIBL_Framework_Path_toolButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
                self.sIBL_Framework_Path_toolButton.setObjectName("sIBL_Framework_Path_toolButton")
                self.sIBL_Framework_Path_groupBox_gridLayout.addWidget(self.sIBL_Framework_Path_toolButton, 0, 1, 1, 1)
                self.sIBL_Executables_groupBox_gridLayout.addWidget(self.sIBL_Framework_Path_groupBox, 0, 1, 1, 1)
                self.sIBLedit_Path_groupBox = QtGui.QGroupBox(self.sIBL_Executables_groupBox)
                self.sIBLedit_Path_groupBox.setMaximumSize(QtCore.QSize(16777215, 64))
                self.sIBLedit_Path_groupBox.setObjectName("sIBLedit_Path_groupBox")
                self.sIBLedit_Path_groupBox_gridLayout = QtGui.QGridLayout(self.sIBLedit_Path_groupBox)
                self.sIBLedit_Path_groupBox_gridLayout.setObjectName("sIBLedit_Path_groupBox_gridLayout")
                self.sIBLedit_Path_lineEdit = QtGui.QLineEdit(self.sIBLedit_Path_groupBox)
                self.sIBLedit_Path_lineEdit.setObjectName("sIBLedit_Path_lineEdit")
                self.sIBLedit_Path_groupBox_gridLayout.addWidget(self.sIBLedit_Path_lineEdit, 0, 0, 1, 1)
                self.sIBLedit_Path_toolButton = QtGui.QToolButton(self.sIBLedit_Path_groupBox)
                self.sIBLedit_Path_toolButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
                self.sIBLedit_Path_toolButton.setObjectName("sIBLedit_Path_toolButton")
                self.sIBLedit_Path_groupBox_gridLayout.addWidget(self.sIBLedit_Path_toolButton, 0, 1, 1, 1)
                self.sIBL_Executables_groupBox_gridLayout.addWidget(self.sIBLedit_Path_groupBox, 0, 0, 1, 1)
                self.Overall_Settings_page_gridLayout.addWidget(self.sIBL_Executables_groupBox, 0, 0, 1, 1)
                self.Others_groupBox = QtGui.QGroupBox(self.Overall_Settings_page)
                self.Others_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Others_groupBox.setFlat(True)
                self.Others_groupBox.setObjectName("Others_groupBox")
                self.Others_groupBox_gridLayout = QtGui.QGridLayout(self.Others_groupBox)
                self.Others_groupBox_gridLayout.setMargin(0)
                self.Others_groupBox_gridLayout.setObjectName("Others_groupBox_gridLayout")
                self.Log_Settings_groupBox = QtGui.QGroupBox(self.Others_groupBox)
                self.Log_Settings_groupBox.setObjectName("Log_Settings_groupBox")
                self.Log_Settings_groupBox_gridLayout = QtGui.QGridLayout(self.Log_Settings_groupBox)
                self.Log_Settings_groupBox_gridLayout.setObjectName("Log_Settings_groupBox_gridLayout")
                self.Verbosity_horizontalLayout = QtGui.QHBoxLayout()
                self.Verbosity_horizontalLayout.setObjectName("Verbosity_horizontalLayout")
                self.Verbose_Level_label = QtGui.QLabel(self.Log_Settings_groupBox)
                self.Verbose_Level_label.setObjectName("Verbose_Level_label")
                self.Verbosity_horizontalLayout.addWidget(self.Verbose_Level_label)
                self.Verbose_Level_comboBox = QtGui.QComboBox(self.Log_Settings_groupBox)
                self.Verbose_Level_comboBox.setObjectName("Verbose_Level_comboBox")
                self.Verbosity_horizontalLayout.addWidget(self.Verbose_Level_comboBox)
                self.Log_Settings_groupBox_gridLayout.addLayout(self.Verbosity_horizontalLayout, 0, 0, 1, 1)
                self.Toggle_Log_Window_pushButton = QtGui.QPushButton(self.Log_Settings_groupBox)
                self.Toggle_Log_Window_pushButton.setMinimumSize(QtCore.QSize(0, 24))
                self.Toggle_Log_Window_pushButton.setObjectName("Toggle_Log_Window_pushButton")
                self.Log_Settings_groupBox_gridLayout.addWidget(self.Toggle_Log_Window_pushButton, 0, 1, 1, 1)
                self.Others_groupBox_gridLayout.addWidget(self.Log_Settings_groupBox, 0, 4, 1, 1)
                self.GPS_Map_groupBox = QtGui.QGroupBox(self.Others_groupBox)
                self.GPS_Map_groupBox.setObjectName("GPS_Map_groupBox")
                self.GPS_Map_groupBox_gridLayout = QtGui.QGridLayout(self.GPS_Map_groupBox)
                self.GPS_Map_groupBox_gridLayout.setObjectName("GPS_Map_groupBox_gridLayout")
                self.Activate_OpenGL_checkBox = QtGui.QCheckBox(self.GPS_Map_groupBox)
                self.Activate_OpenGL_checkBox.setChecked(True)
                self.Activate_OpenGL_checkBox.setObjectName("Activate_OpenGL_checkBox")
                self.GPS_Map_groupBox_gridLayout.addWidget(self.Activate_OpenGL_checkBox, 0, 0, 1, 1)
                self.Activate_Antialiasing_checkBox = QtGui.QCheckBox(self.GPS_Map_groupBox)
                self.Activate_Antialiasing_checkBox.setChecked(True)
                self.Activate_Antialiasing_checkBox.setObjectName("Activate_Antialiasing_checkBox")
                self.GPS_Map_groupBox_gridLayout.addWidget(self.Activate_Antialiasing_checkBox, 0, 1, 1, 1)
                self.Others_groupBox_gridLayout.addWidget(self.GPS_Map_groupBox, 0, 2, 1, 1)
                spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Others_groupBox_gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
                self.Overall_Settings_page_gridLayout.addWidget(self.Others_groupBox, 2, 0, 1, 1)
                spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
                self.Overall_Settings_page_gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
                self.Preferences_toolBox.addItem(self.Overall_Settings_page, "")
                self.Collection_Management_page = QtGui.QWidget()
                self.Collection_Management_page.setGeometry(QtCore.QRect(0, 0, 618, 311))
                self.Collection_Management_page.setObjectName("Collection_Management_page")
                self.Collection_Management_page_gridLayout = QtGui.QGridLayout(self.Collection_Management_page)
                self.Collection_Management_page_gridLayout.setObjectName("Collection_Management_page_gridLayout")
                self.Collections_Paths_groupBox = QtGui.QGroupBox(self.Collection_Management_page)
                self.Collections_Paths_groupBox.setObjectName("Collections_Paths_groupBox")
                self.Collections_Paths_groupBox_gridLayout = QtGui.QGridLayout(self.Collections_Paths_groupBox)
                self.Collections_Paths_groupBox_gridLayout.setContentsMargins(-1, 0, -1, 0)
                self.Collections_Paths_groupBox_gridLayout.setObjectName("Collections_Paths_groupBox_gridLayout")
                self.Collections_Paths_tableWidget = QtGui.QTableWidget(self.Collections_Paths_groupBox)
                self.Collections_Paths_tableWidget.setFrameShape(QtGui.QFrame.Box)
                self.Collections_Paths_tableWidget.setAlternatingRowColors(True)
                self.Collections_Paths_tableWidget.setShowGrid(False)
                self.Collections_Paths_tableWidget.setObjectName("Collections_Paths_tableWidget")
                self.Collections_Paths_tableWidget.setColumnCount(0)
                self.Collections_Paths_tableWidget.setRowCount(0)
                self.Collections_Paths_groupBox_gridLayout.addWidget(self.Collections_Paths_tableWidget, 0, 0, 1, 1)
                self.Collections_Paths_verticalLayout = QtGui.QVBoxLayout()
                self.Collections_Paths_verticalLayout.setObjectName("Collections_Paths_verticalLayout")
                self.Refresh_Collection_pushButton = QtGui.QPushButton(self.Collections_Paths_groupBox)
                self.Refresh_Collection_pushButton.setObjectName("Refresh_Collection_pushButton")
                self.Collections_Paths_verticalLayout.addWidget(self.Refresh_Collection_pushButton)
                self.Edit_Collection_pushButton = QtGui.QPushButton(self.Collections_Paths_groupBox)
                self.Edit_Collection_pushButton.setObjectName("Edit_Collection_pushButton")
                self.Collections_Paths_verticalLayout.addWidget(self.Edit_Collection_pushButton)
                spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
                self.Collections_Paths_verticalLayout.addItem(spacerItem6)
                self.Add_pushButton = QtGui.QPushButton(self.Collections_Paths_groupBox)
                self.Add_pushButton.setObjectName("Add_pushButton")
                self.Collections_Paths_verticalLayout.addWidget(self.Add_pushButton)
                self.Remove_pushButton = QtGui.QPushButton(self.Collections_Paths_groupBox)
                self.Remove_pushButton.setObjectName("Remove_pushButton")
                self.Collections_Paths_verticalLayout.addWidget(self.Remove_pushButton)
                spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
                self.Collections_Paths_verticalLayout.addItem(spacerItem7)
                self.Collections_Paths_groupBox_gridLayout.addLayout(self.Collections_Paths_verticalLayout, 0, 1, 1, 1)
                self.Collection_Management_page_gridLayout.addWidget(self.Collections_Paths_groupBox, 0, 0, 1, 1)
                self.Preferences_toolBox.addItem(self.Collection_Management_page, "")
                self.Online_Update_page = QtGui.QWidget()
                self.Online_Update_page.setGeometry(QtCore.QRect(0, 0, 618, 311))
                self.Online_Update_page.setObjectName("Online_Update_page")
                self.Online_Update_page_gridLayout = QtGui.QGridLayout(self.Online_Update_page)
                self.Online_Update_page_gridLayout.setContentsMargins(-1, 0, -1, 0)
                self.Online_Update_page_gridLayout.setObjectName("Online_Update_page_gridLayout")
                self.Online_Repository_groupBox = QtGui.QGroupBox(self.Online_Update_page)
                self.Online_Repository_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Online_Repository_groupBox.setFlat(True)
                self.Online_Repository_groupBox.setObjectName("Online_Repository_groupBox")
                self.Online_Repository_groupBox_gridLayout = QtGui.QGridLayout(self.Online_Repository_groupBox)
                self.Online_Repository_groupBox_gridLayout.setMargin(0)
                self.Online_Repository_groupBox_gridLayout.setObjectName("Online_Repository_groupBox_gridLayout")
                self.Downloads_groupBox = QtGui.QGroupBox(self.Online_Repository_groupBox)
                self.Downloads_groupBox.setObjectName("Downloads_groupBox")
                self.Downloads_groupBox_gridLayout = QtGui.QGridLayout(self.Downloads_groupBox)
                self.Downloads_groupBox_gridLayout.setObjectName("Downloads_groupBox_gridLayout")
                self.Get_Templates_pushButton = QtGui.QPushButton(self.Downloads_groupBox)
                self.Get_Templates_pushButton.setObjectName("Get_Templates_pushButton")
                self.Downloads_groupBox_gridLayout.addWidget(self.Get_Templates_pushButton, 1, 1, 1, 1)
                self.Get_Help_pushButton = QtGui.QPushButton(self.Downloads_groupBox)
                self.Get_Help_pushButton.setObjectName("Get_Help_pushButton")
                self.Downloads_groupBox_gridLayout.addWidget(self.Get_Help_pushButton, 0, 1, 1, 1)
                self.Online_Repository_groupBox_gridLayout.addWidget(self.Downloads_groupBox, 0, 3, 1, 1)
                self.Online_Updater_groupBox = QtGui.QGroupBox(self.Online_Repository_groupBox)
                self.Online_Updater_groupBox.setObjectName("Online_Updater_groupBox")
                self.Online_Updater_groupBox_gridLayout = QtGui.QGridLayout(self.Online_Updater_groupBox)
                self.Online_Updater_groupBox_gridLayout.setObjectName("Online_Updater_groupBox_gridLayout")
                self.Check_For_New_Releases_pushButton = QtGui.QPushButton(self.Online_Updater_groupBox)
                self.Check_For_New_Releases_pushButton.setObjectName("Check_For_New_Releases_pushButton")
                self.Online_Updater_groupBox_gridLayout.addWidget(self.Check_For_New_Releases_pushButton, 0, 2, 1, 1)
                self.Check_For_New_Releases_checkBox = QtGui.QCheckBox(self.Online_Updater_groupBox)
                self.Check_For_New_Releases_checkBox.setChecked(True)
                self.Check_For_New_Releases_checkBox.setObjectName("Check_For_New_Releases_checkBox")
                self.Online_Updater_groupBox_gridLayout.addWidget(self.Check_For_New_Releases_checkBox, 1, 2, 1, 1)
                self.Ignore_Missing_Templates_checkBox = QtGui.QCheckBox(self.Online_Updater_groupBox)
                self.Ignore_Missing_Templates_checkBox.setChecked(False)
                self.Ignore_Missing_Templates_checkBox.setObjectName("Ignore_Missing_Templates_checkBox")
                self.Online_Updater_groupBox_gridLayout.addWidget(self.Ignore_Missing_Templates_checkBox, 2, 2, 1, 1)
                self.Online_Repository_groupBox_gridLayout.addWidget(self.Online_Updater_groupBox, 0, 1, 1, 1)
                spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Online_Repository_groupBox_gridLayout.addItem(spacerItem8, 0, 2, 1, 1)
                spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
                self.Online_Repository_groupBox_gridLayout.addItem(spacerItem9, 1, 2, 1, 1)
                self.Online_Update_page_gridLayout.addWidget(self.Online_Repository_groupBox, 0, 0, 1, 1)
                self.Preferences_toolBox.addItem(self.Online_Update_page, "")
                self.Preferences_tab_gridLayout.addWidget(self.Preferences_toolBox, 0, 0, 1, 1)
                self.sIBL_GUI_tabWidget.addTab(self.Preferences_tab, "")
                self.Help_tab = QtGui.QWidget()
                self.Help_tab.setObjectName("Help_tab")
                self.Help_tab_gridLayout = QtGui.QGridLayout(self.Help_tab)
                self.Help_tab_gridLayout.setObjectName("Help_tab_gridLayout")
                self.Help_groupBox = QtGui.QGroupBox(self.Help_tab)
                self.Help_groupBox.setObjectName("Help_groupBox")
                self.Help_groupBox_gridLayout = QtGui.QGridLayout(self.Help_groupBox)
                self.Help_groupBox_gridLayout.setObjectName("Help_groupBox_gridLayout")
                self.Help_webView = QtWebKit.QWebView(self.Help_groupBox)
                self.Help_webView.setUrl(QtCore.QUrl("about:blank"))
                self.Help_webView.setObjectName("Help_webView")
                self.Help_groupBox_gridLayout.addWidget(self.Help_webView, 0, 0, 1, 1)
                self.Help_tab_gridLayout.addWidget(self.Help_groupBox, 1, 0, 1, 1)
                self.Help_Files_groupBox = QtGui.QGroupBox(self.Help_tab)
                self.Help_Files_groupBox.setAlignment(QtCore.Qt.AlignCenter)
                self.Help_Files_groupBox.setFlat(True)
                self.Help_Files_groupBox.setObjectName("Help_Files_groupBox")
                self.Help_Files_gridLayout = QtGui.QGridLayout(self.Help_Files_groupBox)
                self.Help_Files_gridLayout.setMargin(0)
                self.Help_Files_gridLayout.setObjectName("Help_Files_gridLayout")
                spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
                self.Help_Files_gridLayout.addItem(spacerItem10, 0, 0, 1, 1)
                self.Available_Topic_groupBox = QtGui.QGroupBox(self.Help_Files_groupBox)
                self.Available_Topic_groupBox.setObjectName("Available_Topic_groupBox")
                self.Available_Topic_groupBox_gridLayout = QtGui.QGridLayout(self.Available_Topic_groupBox)
                self.Available_Topic_groupBox_gridLayout.setObjectName("Available_Topic_groupBox_gridLayout")
                self.Help_Files_comboBox = QtGui.QComboBox(self.Available_Topic_groupBox)
                self.Help_Files_comboBox.setObjectName("Help_Files_comboBox")
                self.Available_Topic_groupBox_gridLayout.addWidget(self.Help_Files_comboBox, 0, 0, 1, 1)
                self.Help_Files_gridLayout.addWidget(self.Available_Topic_groupBox, 0, 1, 1, 1)
                self.Help_tab_gridLayout.addWidget(self.Help_Files_groupBox, 0, 0, 1, 1)
                self.sIBL_GUI_tabWidget.addTab(self.Help_tab, "")
                self.About_tab = QtGui.QWidget()
                self.About_tab.setObjectName("About_tab")
                self.About_gridLayout = QtGui.QGridLayout(self.About_tab)
                self.About_gridLayout.setObjectName("About_gridLayout")
                self.About_label = QtGui.QLabel(self.About_tab)
                self.About_label.setOpenExternalLinks(True)
                self.About_label.setObjectName("About_label")
                self.About_gridLayout.addWidget(self.About_label, 1, 0, 1, 3)
                spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
                self.About_gridLayout.addItem(spacerItem11, 0, 1, 1, 1)
                spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
                self.About_gridLayout.addItem(spacerItem12, 2, 1, 1, 1)
                self.sIBL_GUI_tabWidget.addTab(self.About_tab, "")
                self.sIBL_GUI_centralwidget_gridLayout.addWidget(self.sIBL_GUI_tabWidget, 1, 0, 1, 1)
                sIBL_GUI.setCentralWidget(self.sIBL_GUI_centralwidget)
                self.sIBL_GUI_dockWidget = QtGui.QDockWidget(sIBL_GUI)
                self.sIBL_GUI_dockWidget.setWindowIcon(icon)
                self.sIBL_GUI_dockWidget.setFloating(False)
                self.sIBL_GUI_dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
                self.sIBL_GUI_dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
                self.sIBL_GUI_dockWidget.setObjectName("sIBL_GUI_dockWidget")
                self.sIBL_GUI_dockWidgetContents = QtGui.QWidget()
                self.sIBL_GUI_dockWidgetContents.setObjectName("sIBL_GUI_dockWidgetContents")
                self.sIBL_GUI_dockWidgetContents_gridLayout = QtGui.QGridLayout(self.sIBL_GUI_dockWidgetContents)
                self.sIBL_GUI_dockWidgetContents_gridLayout.setObjectName("sIBL_GUI_dockWidgetContents_gridLayout")
                self.Log_groupBox = QtGui.QGroupBox(self.sIBL_GUI_dockWidgetContents)
                self.Log_groupBox.setObjectName("Log_groupBox")
                self.Log_groupBox_gridLayout = QtGui.QGridLayout(self.Log_groupBox)
                self.Log_groupBox_gridLayout.setObjectName("Log_groupBox_gridLayout")
                self.Log_textEdit = QtGui.QTextEdit(self.Log_groupBox)
                self.Log_textEdit.setMinimumSize(QtCore.QSize(0, 128))
                self.Log_textEdit.setFrameShape(QtGui.QFrame.Box)
                self.Log_textEdit.setAcceptRichText(False)
                self.Log_textEdit.setObjectName("Log_textEdit")
                self.Log_groupBox_gridLayout.addWidget(self.Log_textEdit, 0, 0, 1, 1)
                self.sIBL_GUI_dockWidgetContents_gridLayout.addWidget(self.Log_groupBox, 0, 0, 1, 1)
                self.sIBL_GUI_dockWidget.setWidget(self.sIBL_GUI_dockWidgetContents)
                sIBL_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.sIBL_GUI_dockWidget)
                self.statusBar = QtGui.QStatusBar(sIBL_GUI)
                self.statusBar.setObjectName("statusBar")
                sIBL_GUI.setStatusBar(self.statusBar)

                self.retranslateUi(sIBL_GUI)
                self.sIBL_GUI_tabWidget.setCurrentIndex(0)
                self.Browser_GPS_Map_toolBox.setCurrentIndex(0)
                self.Options_toolBox.setCurrentIndex(0)
                self.Preferences_toolBox.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(sIBL_GUI)

        def retranslateUi(self, sIBL_GUI):
                sIBL_GUI.setWindowTitle(QtGui.QApplication.translate("sIBL_GUI", "sIBL_GUI", None, QtGui.QApplication.UnicodeUTF8))
                self.Collections_Browser_tab.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Collections Browser Tab : Browse The Global Collection, Search And Filter It.", None, QtGui.QApplication.UnicodeUTF8))
                self.Filters_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Filters", None, QtGui.QApplication.UnicodeUTF8))
                self.Collections_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Collections :", None, QtGui.QApplication.UnicodeUTF8))
                self.Collections_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Collections ComboBox :  Global Collection Sub-Collections Filtering.", None, QtGui.QApplication.UnicodeUTF8))
                self.Authors_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Authors :", None, QtGui.QApplication.UnicodeUTF8))
                self.Authors_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Authors ComboBox : Global Collection Authors Filtering.", None, QtGui.QApplication.UnicodeUTF8))
                self.Locations_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Locations :", None, QtGui.QApplication.UnicodeUTF8))
                self.Locations_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Locations ComboBox : Global Collection Locations Filtering.", None, QtGui.QApplication.UnicodeUTF8))
                self.Search_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Search", None, QtGui.QApplication.UnicodeUTF8))
                self.Search_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Search LineEdit : Searches Input Text Through The Global Collection.", None, QtGui.QApplication.UnicodeUTF8))
                self.Browser_GPS_Map_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Browser / GPS Map", None, QtGui.QApplication.UnicodeUTF8))
                self.Collections_listWidget.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Collections List : Double-click An Item To Send It To Import Tab.", None, QtGui.QApplication.UnicodeUTF8))
                self.Browser_GPS_Map_toolBox.setItemText(self.Browser_GPS_Map_toolBox.indexOf(self.Browser_Page), QtGui.QApplication.translate("sIBL_GUI", "Browser", None, QtGui.QApplication.UnicodeUTF8))
                self.Browser_GPS_Map_toolBox.setItemText(self.Browser_GPS_Map_toolBox.indexOf(self.GPS_Map_Page), QtGui.QApplication.translate("sIBL_GUI", "GPS Map", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_tabWidget.setTabText(self.sIBL_GUI_tabWidget.indexOf(self.Collections_Browser_tab), QtGui.QApplication.translate("sIBL_GUI", "Collections Browser", None, QtGui.QApplication.UnicodeUTF8))
                self.Import_tab.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Import Tab : Define Options, Used Template And Other Settings For The Loader Script Generation.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_groupBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "sIBL GroupBox : Infos About The Current sIBL.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "sIBL", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Infos_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Infos", None, QtGui.QApplication.UnicodeUTF8))
                self.Location_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Location", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Author_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Author", None, QtGui.QApplication.UnicodeUTF8))
                self.Shot_Date_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Shot Date", None, QtGui.QApplication.UnicodeUTF8))
                self.Comment_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Comment", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Set_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Preview", None, QtGui.QApplication.UnicodeUTF8))
                self.Preview_label.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Preview Label : Preview Of The Current sIBL.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Options_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Options", None, QtGui.QApplication.UnicodeUTF8))
                self.Edit_In_sIBL_Edit_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Edit In sIBL Edit PushButton : Sends The sIBL File To sIBL Edit.", None, QtGui.QApplication.UnicodeUTF8))
                self.Edit_In_sIBL_Edit_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Edit In sIBL Edit", None, QtGui.QApplication.UnicodeUTF8))
                self.Refresh_sIBL_File_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Refresh sIBL File PushButton : Reloads The Current sIBL File.", None, QtGui.QApplication.UnicodeUTF8))
                self.Refresh_sIBL_File_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Refresh sIBL File", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_sIBL_Folder_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Open sIBL Folder PushButton : Opens Folder Containing The Current sIBL.", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_sIBL_Folder_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Open sIBL Folder", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_groupBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Template GroupBox : Options And Infos About The Current Template And Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Template", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_Infos_groupBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Template Infos GroupBox : Infos About The Current Template.", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_Infos_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Infos", None, QtGui.QApplication.UnicodeUTF8))
                self.Release_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Release", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_Author_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Author", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_Loader_Script_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Loader Script", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_Comment_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Comment", None, QtGui.QApplication.UnicodeUTF8))
                self.Options_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Options", None, QtGui.QApplication.UnicodeUTF8))
                self.Common_Attributes_page.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Common Attributes : Common Attributes Settings Of The Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Options_toolBox.setItemText(self.Options_toolBox.indexOf(self.Common_Attributes_page), QtGui.QApplication.translate("sIBL_GUI", "Common Attributes", None, QtGui.QApplication.UnicodeUTF8))
                self.Additional_Attributes_page.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Additional Attributes : Additional Attributes Settings Of The Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Options_toolBox.setItemText(self.Options_toolBox.indexOf(self.Additional_Attributes_page), QtGui.QApplication.translate("sIBL_GUI", "Additional Attributes", None, QtGui.QApplication.UnicodeUTF8))
                self.Loader_Script_groupBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Loader Script GroupBox : Output Options For The Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Loader_Script_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Loader Script", None, QtGui.QApplication.UnicodeUTF8))
                self.Output_Loader_Script_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Output Loader Script PushButton : Outputs The Loader Script To The \"TMP\" Or \"TMPDIR\" Variable Path. ", None, QtGui.QApplication.UnicodeUTF8))
                self.Output_Loader_Script_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Output Loader Script", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_Output_Folder_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Open Output Folder Script PushButton : Opens Folder Containing The Current Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_Output_Folder_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Open Output Folder", None, QtGui.QApplication.UnicodeUTF8))
                self.Software_Templates_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Selection", None, QtGui.QApplication.UnicodeUTF8))
                self.Edit_Current_Template_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Edit Current Template PushButton : Edits The Current Template In Default Text Editor.", None, QtGui.QApplication.UnicodeUTF8))
                self.Edit_Current_Template_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Edit Current Template", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_Templates_Folder_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Open Templates Folder PushButton : Opens Folder Containing The Templates.", None, QtGui.QApplication.UnicodeUTF8))
                self.Open_Templates_Folder_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Open Templates Folder", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Current Template :", None, QtGui.QApplication.UnicodeUTF8))
                self.Template_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Template ComboBox : Template For The Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Software_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Current Software :", None, QtGui.QApplication.UnicodeUTF8))
                self.Software_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Software ComboBox : Target Application For The Loader Script.", None, QtGui.QApplication.UnicodeUTF8))
                self.Remote_Connection_groupBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Remote Connection GroupBox : Direct Submit Of the Loader Script If The Software Support Remote Connection.", None, QtGui.QApplication.UnicodeUTF8))
                self.Remote_Connection_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Remote Connection", None, QtGui.QApplication.UnicodeUTF8))
                self.Send_To_Software_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Send To Software PushButton : Direct Connection To Target Application If Remote Connection Is Available.", None, QtGui.QApplication.UnicodeUTF8))
                self.Send_To_Software_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Send To Software", None, QtGui.QApplication.UnicodeUTF8))
                self.Port_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Port :", None, QtGui.QApplication.UnicodeUTF8))
                self.Software_Port_spinBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Software Port SpinBox : Opened Port Of The Target 3D Package.", None, QtGui.QApplication.UnicodeUTF8))
                self.Address_label.setText(QtGui.QApplication.translate("sIBL_GUI", "IP :", None, QtGui.QApplication.UnicodeUTF8))
                self.Address_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Ip Address LineEdit : Ip Adress Of The Computer Running The Target 3D Package.", None, QtGui.QApplication.UnicodeUTF8))
                self.Address_lineEdit.setText(QtGui.QApplication.translate("sIBL_GUI", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_tabWidget.setTabText(self.sIBL_GUI_tabWidget.indexOf(self.Import_tab), QtGui.QApplication.translate("sIBL_GUI", "Import", None, QtGui.QApplication.UnicodeUTF8))
                self.Preferences_tab.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Preferences Tab : Define sIBL_GUI Options, Sub Collections Paths, Rtc.", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_Executables_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Custom Executables", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_Text_Editor_Path_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Custom Text Editor", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_Text_Editor_Path_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Custom Text Editor Path LineEdit : Custom Text Editor Path.", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_Text_Editor_Path_toolButton.setText(QtGui.QApplication.translate("sIBL_GUI", "...", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_File_Browser_Path_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Custom File Browser", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_File_Browser_Path_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Custom File Browser Path LineEdit : Current File Browser Path.", None, QtGui.QApplication.UnicodeUTF8))
                self.Custom_File_Browser_Path_toolButton.setText(QtGui.QApplication.translate("sIBL_GUI", "...", None, QtGui.QApplication.UnicodeUTF8))
                self.Templates_Setting_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Templates Settings", None, QtGui.QApplication.UnicodeUTF8))
                self.Templates_Path_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Templates Path", None, QtGui.QApplication.UnicodeUTF8))
                self.Templates_Path_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Templates Path LineEdit : Current Templates Folder.", None, QtGui.QApplication.UnicodeUTF8))
                self.Templates_toolButton.setText(QtGui.QApplication.translate("sIBL_GUI", "...", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_Files_Settings_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Help Files Settings", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_Files_Settings_Path_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Help Files Path", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_Files_Path_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Help Files Path LineEdit : Current Help Files Folder.", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_Files_toolButton.setText(QtGui.QApplication.translate("sIBL_GUI", "...", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Executables_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "sIBL Executables", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Framework_Path_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "sIBL_Framework Path", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Framework_Path_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "sIBL Framework Path LineEdit : Current sIBL_Framework Path.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_Framework_Path_toolButton.setText(QtGui.QApplication.translate("sIBL_GUI", "...", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBLedit_Path_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "sIBLedit Path", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBLedit_Path_lineEdit.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "sIBL Edit Path LineEdit : sIBL Edit Path.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBLedit_Path_toolButton.setText(QtGui.QApplication.translate("sIBL_GUI", "...", None, QtGui.QApplication.UnicodeUTF8))
                self.Others_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Others", None, QtGui.QApplication.UnicodeUTF8))
                self.Log_Settings_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Log", None, QtGui.QApplication.UnicodeUTF8))
                self.Verbose_Level_label.setText(QtGui.QApplication.translate("sIBL_GUI", "Verbose Level :", None, QtGui.QApplication.UnicodeUTF8))
                self.Verbose_Level_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Verbose Level ComboBox : Defines sIBL_GUI Verbose Level : Each Option Comprise The Ones Over It In The List.", None, QtGui.QApplication.UnicodeUTF8))
                self.Toggle_Log_Window_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Toggles Log Window PushButton : Show The Log Window.", None, QtGui.QApplication.UnicodeUTF8))
                self.Toggle_Log_Window_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Toggle Log Window", None, QtGui.QApplication.UnicodeUTF8))
                self.GPS_Map_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "GPS Map", None, QtGui.QApplication.UnicodeUTF8))
                self.Activate_OpenGL_checkBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Activate OpenGL CheckBox : Activate Open GL For The GPS Map.", None, QtGui.QApplication.UnicodeUTF8))
                self.Activate_OpenGL_checkBox.setText(QtGui.QApplication.translate("sIBL_GUI", "Activate OpenGL", None, QtGui.QApplication.UnicodeUTF8))
                self.Activate_Antialiasing_checkBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Activate OpenGL CheckBox : Activate Open GL For The GPS Map.", None, QtGui.QApplication.UnicodeUTF8))
                self.Activate_Antialiasing_checkBox.setText(QtGui.QApplication.translate("sIBL_GUI", "Activate Antialiasing", None, QtGui.QApplication.UnicodeUTF8))
                self.Preferences_toolBox.setItemText(self.Preferences_toolBox.indexOf(self.Overall_Settings_page), QtGui.QApplication.translate("sIBL_GUI", "Overall Settings", None, QtGui.QApplication.UnicodeUTF8))
                self.Collections_Paths_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Collection Paths", None, QtGui.QApplication.UnicodeUTF8))
                self.Collections_Paths_tableWidget.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Collections Paths : Current Sub Collections Paths.", None, QtGui.QApplication.UnicodeUTF8))
                self.Refresh_Collection_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Refresh Collection PushButton : Refresh Global Collection, Reparsing All Directories, Etc...", None, QtGui.QApplication.UnicodeUTF8))
                self.Refresh_Collection_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Refresh Collection", None, QtGui.QApplication.UnicodeUTF8))
                self.Edit_Collection_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Edit", None, QtGui.QApplication.UnicodeUTF8))
                self.Add_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Add PushButton : Add A New Sub Collection.", None, QtGui.QApplication.UnicodeUTF8))
                self.Add_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Add", None, QtGui.QApplication.UnicodeUTF8))
                self.Remove_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Removes PushButton : Remove Selected Sub Collections.", None, QtGui.QApplication.UnicodeUTF8))
                self.Remove_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Remove", None, QtGui.QApplication.UnicodeUTF8))
                self.Preferences_toolBox.setItemText(self.Preferences_toolBox.indexOf(self.Collection_Management_page), QtGui.QApplication.translate("sIBL_GUI", "Collection_Management", None, QtGui.QApplication.UnicodeUTF8))
                self.Online_Repository_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Online Repository", None, QtGui.QApplication.UnicodeUTF8))
                self.Downloads_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Downloads", None, QtGui.QApplication.UnicodeUTF8))
                self.Get_Templates_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Get Templates PushButton : Download / Update Templates From Online Repository.", None, QtGui.QApplication.UnicodeUTF8))
                self.Get_Templates_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Get Latest Templates", None, QtGui.QApplication.UnicodeUTF8))
                self.Get_Help_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Get Help PushButton : Download / Update Help From Online Repository.", None, QtGui.QApplication.UnicodeUTF8))
                self.Get_Help_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Get Latest Online Help", None, QtGui.QApplication.UnicodeUTF8))
                self.Online_Updater_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Online Updater", None, QtGui.QApplication.UnicodeUTF8))
                self.Check_For_New_Releases_pushButton.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Check For New_Releases PushButton : sIBL_GUI Will Check If New Releases Are Available Online.", None, QtGui.QApplication.UnicodeUTF8))
                self.Check_For_New_Releases_pushButton.setText(QtGui.QApplication.translate("sIBL_GUI", "Check For New Releases", None, QtGui.QApplication.UnicodeUTF8))
                self.Check_For_New_Releases_checkBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Enable New Releases Checking CheckBox : sIBL_GUI Will Check If New Releases Are Available On Startup.", None, QtGui.QApplication.UnicodeUTF8))
                self.Check_For_New_Releases_checkBox.setText(QtGui.QApplication.translate("sIBL_GUI", "Check For New Releases On Startup", None, QtGui.QApplication.UnicodeUTF8))
                self.Ignore_Missing_Templates_checkBox.setText(QtGui.QApplication.translate("sIBL_GUI", "Ignore Missing Templates", None, QtGui.QApplication.UnicodeUTF8))
                self.Preferences_toolBox.setItemText(self.Preferences_toolBox.indexOf(self.Online_Update_page), QtGui.QApplication.translate("sIBL_GUI", "Online Update", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_tabWidget.setTabText(self.sIBL_GUI_tabWidget.indexOf(self.Preferences_tab), QtGui.QApplication.translate("sIBL_GUI", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_tab.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Help Tab : Show The Current Help File.", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_Files_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Help Files", None, QtGui.QApplication.UnicodeUTF8))
                self.Available_Topic_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "Available Topics", None, QtGui.QApplication.UnicodeUTF8))
                self.Help_Files_comboBox.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Help Files ComboBox : Available Help Files Topics.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_tabWidget.setTabText(self.sIBL_GUI_tabWidget.indexOf(self.Help_tab), QtGui.QApplication.translate("sIBL_GUI", "Help", None, QtGui.QApplication.UnicodeUTF8))
                self.About_tab.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "About Tab : Random Stuff About sIBL_GUI.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_tabWidget.setTabText(self.sIBL_GUI_tabWidget.indexOf(self.About_tab), QtGui.QApplication.translate("sIBL_GUI", "About", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_dockWidget.setStatusTip(QtGui.QApplication.translate("sIBL_GUI", "Log Window : Show sIBL_GUI log, This Window Is Tearable.", None, QtGui.QApplication.UnicodeUTF8))
                self.sIBL_GUI_dockWidget.setWindowTitle(QtGui.QApplication.translate("sIBL_GUI", "Log Window", None, QtGui.QApplication.UnicodeUTF8))
                self.Log_groupBox.setTitle(QtGui.QApplication.translate("sIBL_GUI", "sIBL_GUI", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import sIBL_GUI_rc
import sIBL_GUI_rc
import sIBL_GUI_rc
import sIBL_GUI_rc
import sIBL_GUI_rc
